// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"database/sql"
	"github.com/Oskarbayy/partyfinder-backend/internal/products"
)

// Injectors from wire.go:

func InitializeProductService(db *sql.DB) (*products.ProductService, error) {
	iProductRepository := products.NewProductRepository(db)
	productService := products.NewProductService(iProductRepository)
	return productService, nil
}
